### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ruslan-garaev** [xkxd/gulp-html-partial#1]
Hi.
At first thanks for your work. Gulp-html-partial is what I looked for.

When I tried to check how the plugin works (https://runkit.com/npm/gulp-html-partial), there error occurred – "SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode". I hope you'll have time to check it.

**Comment by xkxd** [comment]
@ruslan-garaev , sorry for that serious delay with responding to your report. Issue you mentioned has been fixed with https://github.com/xkxd/gulp-html-partial/commit/0ff4ac130cbfb4c6c898e83d933df5dbb416be78

Let me know, if some other problems occurred :)
